version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    depends_on:
      - db
    tty: true
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Z8o5vuzV
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
